version: 2.1

executors:
  golang:
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.18
    resource_class: medium+

commands:
  build-and-persist-plugin-binary:
    parameters:
      GOOS:
        type: string
      GOARCH:
        default: "amd64"
        type: string
    steps:
      - checkout
      - run: GOOS=<< parameters.GOOS >> GOARCH=<<parameters.GOARCH>> go build -o ./pkg/packer_plugin_qemu_<< parameters.GOOS >>_<< parameters.GOARCH >> .
      - run: zip ./pkg/packer_plugin_qemu_<< parameters.GOOS >>_<< parameters.GOARCH >>.zip ./pkg/packer_plugin_qemu_<< parameters.GOOS >>_<< parameters.GOARCH >>
      - run: rm ./pkg/packer_plugin_qemu_<< parameters.GOOS >>_<< parameters.GOARCH >>
      - persist_to_workspace:
          root: .
          paths:
            - ./pkg/

# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
jobs:
  build_linux:
    executor: golang
    steps:
      - build-and-persist-plugin-binary:
          GOOS: linux
  build_windows:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: windows
  build_darwin:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: darwin
      - build-and-persist-plugin-binary:
          GOOS: darwin
          GOARCH: arm64
  build_freebsd:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: freebsd
  build_illumos:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: illumos
  build_solaris:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: solaris
  build_openbsd:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: openbsd
  build_linux_ppc64le:
    executor: golang
    working_directory: ~/go/src/github.com/hashicorp/packer-plugin-qemu
    steps:
      - build-and-persist-plugin-binary:
          GOOS: linux
          GOARCH: ppc64le
  store_artifacts:
    executor: golang
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: ./pkg/
          destination: /

workflows:
  version: 2
  build_plugin_binaries:
    jobs:
      - build_darwin
      - build_freebsd
      - build_linux
      - build_openbsd
      - build_illumos
      - build_solaris
      - build_windows
      - build_linux_ppc64le
      - store_artifacts:
          requires:
            - build_darwin
            - build_freebsd
            - build_linux
            - build_openbsd
            - build_illumos
            - build_solaris
            - build_windows
            - build_linux_ppc64le